version: 2
notify:
  webhooks:
    - url: https://webhook.atomist.com/atomist/circle/teams/T7MG11DK3
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
    working_directory: ~/repo/clojure/anagram
    environment:
      LEIN_ROOT: "true"
    steps:
      - checkout
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein test

