version: 2
notify:
  webhooks:
    - url: https://webhook.atomist.com/atomist/circle/teams/T7MG11DK3
jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.8.1-browsers
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ find . -name project.clj -type f -exec md5sum "{}" + | md5sum }}
          - v1-dependencies-
      - run: lein-deps.sh
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ find . -name project.clj -type f -exec md5sum "{}" + | md5sum }}
      - run: lein-test.sh
